# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('datetime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('gps_traces', models.ManyToManyField(to='auto_report.GpsTrace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('mode', models.CharField(choices=[('MAN', 'manual driving'), ('AUT', 'autonomous driving')], max_length=3)),
                ('distance', models.IntegerField()),
                ('roads', models.ManyToManyField(to='auto_report.Road')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('utc_uid', models.IntegerField()),
                ('card_hash', models.IntegerField()),
                ('is_autorized_to_change_mode', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(to='auto_report.User'),
        ),
        migrations.AddField(
            model_name='gpstrace',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_report.Session'),
        ),
    ]
