# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstrace',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_traces', to='auto_report.Session'),
        ),
        migrations.AlterField(
            model_name='road',
            name='gps_traces',
            field=models.ManyToManyField(related_name='roads', to='auto_report.GpsTrace'),
        ),
        migrations.AlterField(
            model_name='session',
            name='roads',
            field=models.ManyToManyField(related_name='sessions', to='auto_report.Road'),
        ),
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='sessions', to='auto_report.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utc_uid',
            field=models.IntegerField(unique=True),
        ),
    ]
