# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0003_auto_20170921_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='city',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='road',
            name='kind',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('name', 'city')]),
        ),
    ]
