# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0003_auto_20170921_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('vin_code', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GpsPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=7)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=5)),
                ('track', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gpstrace',
            name='session',
        ),
        migrations.RemoveField(
            model_name='road',
            name='gps_traces',
        ),
        migrations.RemoveField(
            model_name='session',
            name='roads',
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('MAN', 'Manual driving'), ('COP', 'Cooperative driving'), ('AUT', 'Autonomous driving')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='GpsTrace',
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='auto_report.Road'),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='auto_report.Session'),
        ),
        migrations.AddField(
            model_name='session',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auto_report.Car'),
            preserve_default=False,
        ),
    ]
