# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0004_auto_20171008_1239'),
        ('auto_report', '0004_auto_20171009_2353'),
    ]

    operations = [
    ]
