# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0005_merge_20171012_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.BigIntegerField(),
        ),
    ]
