# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_report', '0007_auto_20171109_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
